### ISSUE TITLE
Issue with Adjust SDK version 5.0.1 - Missing Dependency

### ISSUE THREAD

**Issue by fkocak2505** [adjust/android_sdk#625]
Hello,

While integrating Adjust SDK version 5.0.1 in our Android project, we encountered an issue related to a missing dependency. Below is the error log:

`Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find adjust-android-signature-3.35.1.aar (com.adjust.signature:adjust-android-signature:3.35.1).

Searched in the following locations:
https://repo.maven.apache.org/maven2/com/adjust/signature/adjust-android-signature/3.35.1/adjust-android-signature-3.35.1.aar
https://repo.maven.apache.org/maven2/com/adjust/signature/adjust-android-signature/3.35.1/adjust-android-signature-3.35.1.jar`

It appears that the required artifact com.adjust.signature:adjust-android-signature:3.35.1 is not available at the specified Maven repository URLs.

Steps to Reproduce:

- Add Adjust SDK version 5.0.1 to the project dependencies.
- Attempt to sync Gradle.
- The error is thrown during the dependency resolution process.

Expected Behavior:

-The SDK should resolve all dependencies correctly and build without errors.

Actual Behavior:
The build fails due to the missing artifact.

Could you please check if the artifact is correctly published or if there are additional configuration steps needed to resolve this dependency?

Thank you for your assistance.

**Comment by Spaown** [comment]
We were using it for a few weeks as well and it just broke while rebuilding the project disrupting the work of everyone here

**Comment by cemtufekci** [comment]
yeah it fails right now because of 404, though we are not using signature library explicitly. Waiting for your urgent assistance.

**Comment by emreozerdev** [comment]
For temporarily solution:

1. Add following code to project's build.gradle.kts
`
allprojects {
    configurations.all {
        resolutionStrategy {
            force("com.adjust.signature:adjust-android-signature:3.35.0")
        }
    }
}
`
2. After that add below dependecy to libs.versions.toml file
adjust-android-signature = { module = "com.adjust.signature:adjust-android-signature", version = "3.35.0" }

**Comment by G00fY2** [comment]
Reason is that adjust uses version range for their internal `adjust-android-signature` dependency, which is bad practise and makes it impossible to get reproducable builds: https://docs.gradle.org/current/userguide/dependency_versions.html

Issue is this line in their build config: https://github.com/adjust/android_sdk/blob/c0f78d2ec77dfacbf53870883b9d5b0e6ca8c731/Adjust/sdk-core/build.gradle#L223

I would vote for always also bump the core SDK if there are changes for the `adjust-android-signature` to prevent this current issue.

**Comment by rscloura** [comment]
Hello everyone,

Due to a network failure, version 3.35.1 Signature artifacts failed to be properly uploaded to Maven. We are currently fixing the issue, and it should be resolved very shortly. Until the issue is resolved, you may manually target a previous version, by altering the Gradle config to
```
dependencies {
    implementation('com.adjust.sdk:adjust-android:5.0.1') {
        exclude group: 'com.adjust.signature', module: 'adjust-android-signature'
    }
...
```
and explicitly adding
```
implementation 'com.adjust.signature:adjust-android-signature:3.35.0'
```
similar to what's already been suggested in previous comments.

We sincerely apologise for the inconvenience, and we will let you know once the issue is resolved.

**Comment by hamz4k** [comment]
@G00fY2 100%, bad practice which led to breaking people's builds which is not OK, as a workaround we've locked the dependency version `adjust-android-signature` to 3.35.0

**Comment by G00fY2** [comment]
> ```
> allprojects {
>     configurations.all {
>         resolutionStrategy {
>             force("com.adjust.signature:adjust-android-signature:3.35.0")
>         }
>     }
> }
> ```
No need to force this library. Declaring the dependency with strict version is sufficient in this case (see [Gradle docs](https://docs.gradle.org/current/userguide/dependency_versions.html#sec:strict-version-consequences)):

> Strict versions effectively act like forced versions.

**Comment by oheyadam** [comment]
This is the second time we have issues because the maintainers of this SDK refuse to follow industry standards and _actually_ release a new version of their libraries when they need to. [This](https://github.com/adjust/android_sdk/blob/c0f78d2ec77dfacbf53870883b9d5b0e6ca8c731/Adjust/sdk-core/build.gradle#L223) should be illegal.

**Comment by rscloura** [comment]
Hello again. A new version (v3.35.2) has been uploaded to Maven, and should now be available normally. The issue has been resolved. Thank you for your patience, and please accept our apologies once more.

**Comment by KiritoMC03** [comment]
Hi!
@rscloura Can you push you Unity-temp to upload fix too? Because we alse have this problem during Unity builds =)

**Comment by cemtufekci** [comment]
> Hello again. A new version (v3.35.2) has been uploaded to Maven, and should now be available normally. The issue has been resolved. Thank you for your patience, and please accept our apologies once more.

5.0.1 still tries to find 3.35.1 and gives error.

**Comment by uerceg** [comment]
Hi guys,

I want to apologize one more time for all the inconveniences this issue has caused you. Reason for letting latest signature library version always to be pulled was to provide more seamless way for users to receive anti-spoofing related updates and protection. However, we hear you and also understand that the stability of the entire mechanism is of utmost importance. As of next update we will be making the SDK to depend on the specific signature library version to avoid issue like this in the future and we will be propagating this update as soon as possible to Unity, Flutter, React Native and Cordova SDKs as well.

Sorry one more time and we appreciate all the feedback on this matter.

We will keep you posted on the rollout of the updates.

Cheers

**Comment by cemtufekci** [comment]
> Hi guys,
> 
> I want to apologize one more time for all the inconveniences this issue has caused you. Reason for letting latest signature library version always to be pulled was to provide more seamless way for users to receive anti-spoofing related updates and protection. However, we hear you and also understand that the stability of the entire mechanism is of utmost importance. As of next update we will be making the SDK to depend on the specific signature library version to avoid issue like this in the future and we will be propagating this update as soon as possible to Unity, Flutter, React Native and Cordova SDKs as well.
> 
> Sorry one more time and we appreciate all the feedback on this matter.
> 
> We will keep you posted on the rollout of the updates.
> 
> Cheers

The thing is, android sdk is still not working properly. We are not using the signature sdk explicitly. I think you should either upload a 3.35.1 aar file to the maven, or declare the newest aar file (3.35.2) to your pom. Developers may solve the build issue by adding a resolution strategy to their gradle file but this is not a proper solution for that issue.

**Comment by farkasadam** [comment]
@rscloura, @uerceg, as the others mentioned, the issue is still unresolved. Could you please provide an update on when we can expect the fix?

**Comment by uerceg** [comment]
SDK v5.0.2 update is on its way with the fix. We'll keep you posted.

**Comment by uerceg** [comment]
[SDK v5.0.2](https://github.com/adjust/android_sdk/releases/tag/v5.0.2) should now hopefully be live and hopefully solve this issue. Looking forward to hear back from you.

**Comment by Faltenreich** [comment]
@uerceg Thank you for your quick response, for acknowledging the issue with version ranges and acting upon it.

For us `com.adjust.sdk:adjust-android:5.0.1` is working fine again without a resolutionStrategy for `com.adjust.signature:adjust-android-signature`. We are not experiencing the problems @cemtufekci described and are therefore not forced to update to `com.adjust.sdk:adjust-android:5.0.2`.

Thank you all for your input!

**Comment by G00fY2** [comment]
@uerceg Thanks for the quick hotfix. 5.0.2 fixes the issue. 🥳

**Comment by uerceg** [comment]
Thank you for letting us know, and apologies once again to everyone for yesterday's inconvenience. 🙏

**Comment by cemtufekci** [comment]
bumped version to 5.0.2 and it's working now, thank you

**Comment by Faltenreich** [comment]
@uerceg I am confused. 5.0.2 includes the broken version 3.35.0 of adjust-signature instead of the fixed version 3.35.1. Why does this seem to work?

**Comment by uerceg** [comment]
@Faltenreich Updates that 3.35.1 brought were mostly aimed to improve things for iOS users and due to policy in versioning on our end, those updates are being shipped on both platforms. So just playing it safely in lights of yesterday's Maven hickups, we went for 3.35.0 version. But it should make no difference for the Android users. Going forward, SDK updates will be picking up 3.35.2++.

In case you have any other questions, feel free to ping.

**Comment by Faltenreich** [comment]
@uerceg My bad, I mixed up the versions. 5.0.2 including 3.35.0 works just fine. Thanks for clearing up my confusion and have a nice day!

**Comment by uerceg** [comment]
No problemo, have a great one, too!

**Comment by fkocak2505** [comment]
Thanks for the quick response and problem resolution. It works without any problems in version 5.0.2. 🥳
